application: time-parser
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: .*
  script: main.py