application: time-parser
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: index\.html

- url: /index.html
  static_files: static/index.html
  upload: index\.html

- url: /css
  static_dir: static/css

- url: .*
  script: main.py